In [1]:
import tensorflow as tf
import numpy as np

### 1. 填充（Padding）

    - tf.Pad(x, paddings)

In [3]:
a = tf.constant([1, 2, 3, 4, 5, 6])
b = tf.constant([6, 5, 4, 3])
b = tf.pad(b, [[0, 2]]) # 左边不填充，右边填充 2 个

In [5]:
b

<tf.Tensor: id=6, shape=(6,), dtype=int32, numpy=array([6, 5, 4, 3, 0, 0])>

In [6]:
tf.stack([a, b], axis=0)

<tf.Tensor: id=7, shape=(2, 6), dtype=int32, numpy=
array([[1, 2, 3, 4, 5, 6],
       [6, 5, 4, 3, 0, 0]])>

### 2. 复制（Copying）

    - tf.tile(x, multiples)

In [8]:
x = tf.random.normal([4, 32, 32, 3])
y = tf.tile(x, [2, 3, 3, 1])
y.shape

TensorShape([8, 96, 96, 3])

### 3. 数据限幅

- `tf.maximum(x, a)`实现数据的下限幅：𝑥 ∈ [𝑎,+∞)；
-  `tf.minimum(x, a)`实现数据的上限幅：𝑥 ∈ (−∞,𝑎]，
- `tf.clip_by_value(x,2,7)`

In [9]:
x = tf.range(9)
tf.maximum(x, 2) # 下限幅 2

<tf.Tensor: id=21, shape=(9,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8])>

In [10]:
tf.minimum(x, 7) # 上限幅 7

<tf.Tensor: id=23, shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 7])>

In [11]:
tf.minimum(tf.maximum(x,2),7) # 限幅为 2~7 

<tf.Tensor: id=27, shape=(9,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 7])>

In [12]:
tf.clip_by_value(x,2,7) # 限幅为 2~7 

<tf.Tensor: id=31, shape=(9,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 7])>

### 4. 高级操作

- `tf.gather(x, [], axis)`:根据索引号收集数据
- `tf.gather_nd(x, [[]])`:可以通过指定每次采样的坐标来实现采样多个点的目的
- `tf.boolean_mask(x, mask, axis)`:通过给定掩码(mask)的方式采样

In [17]:
x = tf.random.uniform([4,5,8],maxval=100,dtype=tf.int32) 

In [18]:
tf.gather(x,[0,1],axis=0) # 在班级维度收集第 1-2 号班级成绩册 

<tf.Tensor: id=52, shape=(2, 5, 8), dtype=int32, numpy=
array([[[99, 80, 12, 96, 77, 56, 31, 89],
        [98, 53,  2, 88, 26, 63, 44,  7],
        [58, 26, 71, 80, 52, 45, 28, 41],
        [78, 94, 65, 97, 90, 47, 51, 90],
        [63, 78, 37, 75, 88, 22,  6, 97]],

       [[ 0, 77, 16,  0, 57, 52, 55, 62],
        [57, 41, 76, 69, 42, 93, 30,  8],
        [55, 81, 49, 88, 84, 27,  8, 79],
        [67, 61, 81, 50, 96, 48, 78, 79],
        [29, 92, 56, 66, 52, 42, 64, 63]]])>

In [20]:
tf.gather(x,[0,2,4],axis=1)

<tf.Tensor: id=55, shape=(4, 3, 8), dtype=int32, numpy=
array([[[99, 80, 12, 96, 77, 56, 31, 89],
        [58, 26, 71, 80, 52, 45, 28, 41],
        [63, 78, 37, 75, 88, 22,  6, 97]],

       [[ 0, 77, 16,  0, 57, 52, 55, 62],
        [55, 81, 49, 88, 84, 27,  8, 79],
        [29, 92, 56, 66, 52, 42, 64, 63]],

       [[26, 11, 58, 38, 15, 90, 78, 91],
        [60, 32, 73, 89, 86, 33, 11, 88],
        [87, 55, 30, 86, 97, 80, 41, 16]],

       [[36, 53,  0, 72,  0, 41, 83, 44],
        [84, 16,  3, 76, 85, 99, 41, 29],
        [31, 89, 19, 64, 42, 97, 38, 86]]])>

In [21]:
tf.gather_nd(x,[[1,1],[2,2],[3,3]]) 

<tf.Tensor: id=57, shape=(3, 8), dtype=int32, numpy=
array([[57, 41, 76, 69, 42, 93, 30,  8],
       [60, 32, 73, 89, 86, 33, 11, 88],
       [36, 21, 40, 64, 25, 47, 69, 58]])>