## Fancy Indexing

In [1]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [3]:
x[3:8]

array([3, 4, 5, 6, 7])

In [4]:
x[2:9:2]

array([2, 4, 6, 8])

In [6]:
ind = [3, 5, 8]
x[ind]

array([3, 5, 8])

#### 二维数组

In [7]:
ind = np.array([[0, 2], [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [9]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
# 取到[0, 1], [1, 2], [2, 3]三个坐标的值
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [11]:
X[0, col]

array([1, 2, 3])

In [13]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

#### 使用布尔值

In [14]:
col = [True, False, True, True]

In [15]:
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

### numpy.array 的比较

In [16]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [18]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [19]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [20]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [21]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

#### count  any  all

In [23]:
x 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
np.sum(x <= 3)

4

In [26]:
np.count_nonzero(x <= 3)

4

In [27]:
np.any(x == 0)

True

In [28]:
np.any(x < 0)

False

In [29]:
np.all(x > 0)

False

In [30]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
np.sum(X % 2 == 0) # 查看矩阵 X 中有多少偶数 

8

In [32]:
np.sum(X % 2 == 0, axis=1) # 沿着列的方向，看有多少偶数

array([2, 2, 2, 2])

In [33]:
np.sum(X % 2 == 0, axis=0) # 沿着行的方向，看有多少偶数

array([4, 0, 4, 0])

 #### 布尔组合

In [34]:
np.sum((x > 3) & (x < 9))

5

In [35]:
np.sum((x % 2 == 0) | (x > 10))

11

In [36]:
np.sum(~(x == 0)) # 非

15

In [37]:
x[x<5]

array([0, 1, 2, 3, 4])

In [38]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

### 复杂组合

In [39]:
X[X[:, 3] % 3 == 0, :] # 取出最后一列可以被 3 整除的行

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [40]:
X[X[:, 3] % 3 == 0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])