# TensorFlow 张量创建

### 1. 数值类型

- 必须通过 tensorflow 规定的方式去创建张量，而不能使用Python语言的标准变量创建方式

In [1]:
import tensorflow as tf

In [3]:
a = 1.2
b = tf.constant(1.2)
type(a), type(b), tf.is_tensor(b)

(float, tensorflow.python.framework.ops.EagerTensor, True)

In [4]:
x = tf.constant([1, 2., 3.3])
x

<tf.Tensor: id=2, shape=(3,), dtype=float32, numpy=array([1. , 2. , 3.3], dtype=float32)>

In [5]:
x.numpy() # 返回 Numpy.array 类型的数据，方便导出数据到系统其他模块

array([1. , 2. , 3.3], dtype=float32)

In [6]:
x.shape

TensorShape([3])

In [7]:
a = tf.constant([[1, 2], [3, 4]])

In [8]:
a, a.shape

(<tf.Tensor: id=3, shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>, TensorShape([2, 2]))

**三维张量**

In [9]:
a = tf.constant([[1, 2], [3, 4], [5, 6]])
a, a.shape

(<tf.Tensor: id=4, shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>, TensorShape([3, 2]))

### 2. 字符串类型

In [18]:
a = tf.constant('Hello, Tensorflow!')
a

<tf.Tensor: id=13, shape=(), dtype=string, numpy=b'Hello, Tensorflow!'>

In [19]:
tf.strings.lower(a)

<tf.Tensor: id=14, shape=(), dtype=string, numpy=b'hello, tensorflow!'>

### 3. 布尔类型

In [20]:
a = tf.constant(True)
a

<tf.Tensor: id=15, shape=(), dtype=bool, numpy=True>

In [21]:
a = tf.constant([True, False])
a

<tf.Tensor: id=16, shape=(2,), dtype=bool, numpy=array([ True, False])>

In [23]:
a = tf.constant(True)

In [24]:
a == True

<tf.Tensor: id=22, shape=(), dtype=bool, numpy=True>

### 4. 数值精度

In [27]:
a = tf.constant(123456789, dtype=tf.int16)
b = tf.constant(123456789, dtype=tf.int32)

In [28]:
a

<tf.Tensor: id=27, shape=(), dtype=int16, numpy=-13035>

In [29]:
b

<tf.Tensor: id=28, shape=(), dtype=int32, numpy=123456789>

**转换精度**

- 布尔型与整型之间是可以相互转换的
- 一般默认 0 表示 False， 1 表示 True， 非 0 数字都为 True

In [30]:
print('before:', a.dtype)
if a.dtype != tf.float32:
    a = tf.cast(a, tf.float32)
print('after:', a.dtype)

before: <dtype: 'int16'>
after: <dtype: 'float32'>


### 5. 创建张量

- tf.Variable

In [31]:
a = tf.constant([-1, 0, 1, 2])
aa = tf.Variable(a)
aa

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([-1,  0,  1,  2])>

In [32]:
aa.name, aa.trainable

('Variable:0', True)

**也可以直接创建 Variable**

In [34]:
a = tf.Variable([1, 2], [3, 4])
a

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

**创建全 0 全 1 的 标量**

In [35]:
tf.zeros([])

<tf.Tensor: id=54, shape=(), dtype=float32, numpy=0.0>

In [36]:
tf.ones([])

<tf.Tensor: id=55, shape=(), dtype=float32, numpy=1.0>

**创建全 0 全 1 的 向量**

In [37]:
tf.zeros([1]), tf.ones([1])

(<tf.Tensor: id=58, shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Tensor: id=61, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)

**创建全 0 全 1 的 矩阵**

In [39]:
tf.zeros([2, 2])

<tf.Tensor: id=64, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

**tf.zeros_like 和 tf.ones_like**

In [40]:
a = tf.ones([2, 4])
tf.zeros_like(a)

<tf.Tensor: id=68, shape=(2, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

**tf.fill(shape, value)**

In [41]:
tf.fill([], -1)

<tf.Tensor: id=71, shape=(), dtype=int32, numpy=-1>

In [42]:
tf.fill([1], -1)

<tf.Tensor: id=74, shape=(1,), dtype=int32, numpy=array([-1])>

In [43]:
tf.fill([2, 3], 999)

<tf.Tensor: id=77, shape=(2, 3), dtype=int32, numpy=
array([[999, 999, 999],
       [999, 999, 999]])>

**创建已知分布的张量**

- 正太分布（Normal Distribution） 
      - tf.random.normal(shape, mean=0.0, stddev=1.0)

In [44]:
tf.random.normal([2, 2])

<tf.Tensor: id=83, shape=(2, 2), dtype=float32, numpy=
array([[ 0.43073112, -0.21019234],
       [-0.7568673 ,  0.6170561 ]], dtype=float32)>

In [45]:
tf.random.normal([2, 2], mean=1, stddev=2)

<tf.Tensor: id=89, shape=(2, 2), dtype=float32, numpy=
array([[ 1.3126788,  4.05105  ],
       [ 1.9362738, -2.979116 ]], dtype=float32)>

- 均值分布（Uniform Distribution）
      - tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32)

In [46]:
tf.random.uniform([2, 2])

<tf.Tensor: id=96, shape=(2, 2), dtype=float32, numpy=
array([[0.7881533 , 0.50970817],
       [0.6180254 , 0.28644907]], dtype=float32)>

In [47]:
tf.random.uniform([2, 2], maxval=10, dtype=tf.int32)

<tf.Tensor: id=100, shape=(2, 2), dtype=int32, numpy=
array([[6, 6],
       [5, 9]])>

**创建序列**

- tf.range(start,limit, delta) 函数实现

In [48]:
tf.range(10)

<tf.Tensor: id=104, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [49]:
tf.range(10, delta=2)

<tf.Tensor: id=108, shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8])>

In [50]:
tf.range(1, 10, 2)

<tf.Tensor: id=112, shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>