# TensorFlow 基础（2）

### 1. 索引

In [1]:
import tensorflow as tf

In [2]:
x = tf.random.normal([4, 32, 32, 3])

In [3]:
# 取第一张图片第 2 行， 第 3 列，B 通道
x[0][1][2][1]

<tf.Tensor: id=21, shape=(), dtype=float32, numpy=0.53999984>

In [4]:
# 也可以如下写法
x[0, 1, 2, 1]

<tf.Tensor: id=25, shape=(), dtype=float32, numpy=0.53999984>

### 2. 切片

In [5]:
# 读取第 2，3 张图片的第 2 行第 3 列
x[1:3, 1, 2]

<tf.Tensor: id=29, shape=(2, 3), dtype=float32, numpy=
array([[-0.72322774, -0.77570975, -3.8933163 ],
       [ 0.3169489 , -0.5193166 , -0.02393725]], dtype=float32)>

In [6]:
# 读取第 1-2 张图片的 G/B 通道数据
# x[0:2,...,1:] 

### 3. 维度变换

**改变维度**
**reshape()**

In [7]:
x = tf.range(96)

In [8]:
x = tf.reshape(x, [2, 4, 4, 3])

**x.ndim 和 x.shape**

In [9]:
x.shape

TensorShape([2, 4, 4, 3])

In [10]:
x.ndim

4

**增加维度**

      - tf.expend_dims(x, axis)

In [11]:
x = tf.random.uniform([4, 4], maxval=10, dtype=tf.int32)
y = tf.random.uniform([4, 4], maxval=10, dtype=tf.int32)

In [12]:
x

<tf.Tensor: id=39, shape=(4, 4), dtype=int32, numpy=
array([[0, 0, 2, 7],
       [5, 8, 3, 0],
       [1, 7, 7, 0],
       [9, 8, 1, 9]])>

In [13]:
# 在最前面插入一个维度
x = tf.expand_dims(x, axis=0)

In [14]:
x.shape

TensorShape([1, 4, 4])

In [15]:
x

<tf.Tensor: id=45, shape=(1, 4, 4), dtype=int32, numpy=
array([[[0, 0, 2, 7],
        [5, 8, 3, 0],
        [1, 7, 7, 0],
        [9, 8, 1, 9]]])>

In [16]:
# 在 y 的最后面插入一个维度
y = tf.expand_dims(y, axis=2)

In [17]:
y.shape

TensorShape([4, 4, 1])

In [18]:
y

<tf.Tensor: id=47, shape=(4, 4, 1), dtype=int32, numpy=
array([[[0],
        [1],
        [5],
        [6]],

       [[6],
        [6],
        [8],
        [3]],

       [[2],
        [1],
        [9],
        [4]],

       [[1],
        [1],
        [6],
        [0]]])>

**删除维度**

- 每次只能删除一个维度
- 如果不指定维度参数 axis，即 tf.squeeze(x)，那么他会默认删除所有长度为 1 的维度
      - tf.squeeze(x, axis)

In [19]:
# 删除 x 第一个维度
x = tf.squeeze(x, axis=0)

In [20]:
x.shape

TensorShape([4, 4])

In [21]:
# 删除 y 的最后一个维度
y = tf.squeeze(y, axis=2)

In [22]:
y.shape

TensorShape([4, 4])

**交换维度**

- 注意：交换维度。改变了张量的**存储顺序**，同时也改变了张量的**视图**
      - tf.transpose(x, perm)

In [23]:
x = tf.random.normal([2, 32, 32, 3])

In [24]:
x.shape

TensorShape([2, 32, 32, 3])

In [25]:
y = tf.transpose(x, perm=[0, 3, 1, 2])

In [26]:
y.shape

TensorShape([2, 3, 32, 32])

**数据复制**

    - tf.tile(b, multiples)

In [27]:
b = tf.constant([1, 2, 3])

# 也可以使用 reshape 方法
# b = tf.reshape(b, [-1, 3])
b = tf.expand_dims(b, axis=0)

In [28]:
b

<tf.Tensor: id=60, shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [29]:
b = tf.tile(b, multiples=[2, 1])

In [30]:
b

<tf.Tensor: id=62, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]])>

In [31]:
b.shape

TensorShape([2, 3])

In [32]:
# -------------------
x = tf.range(4)
x = tf.reshape(x, [2, 2])
x

<tf.Tensor: id=68, shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]])>

In [33]:
x = tf.tile(x, multiples=[1, 2])
x

<tf.Tensor: id=70, shape=(2, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3]])>

In [34]:
x = tf.tile(x, multiples=[2, 1])
x

<tf.Tensor: id=72, shape=(4, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]])>

**Broadcasting**

    - tf.broadcase_to(x, new_shape)

In [39]:
A = tf.random.normal([32, 1])

In [40]:
A.shape

TensorShape([32, 1])

In [41]:
A = tf.broadcast_to(A, [2, 32, 32, 3])

In [42]:
A.shape

TensorShape([2, 32, 32, 3])

### 4. 数学运算

**加减乘除**

    - tf.add
    - tf.subtract
    - tf.multiply
    - tf.divide
- 也可以使用 + - * / 运算符
- 整除： //
- 余除： %

In [43]:
a = tf.range(5)
b = tf.constant(2)
a // b

<tf.Tensor: id=108, shape=(5,), dtype=int32, numpy=array([0, 0, 1, 1, 2])>

In [44]:
a % b

<tf.Tensor: id=109, shape=(5,), dtype=int32, numpy=array([0, 1, 0, 1, 0])>

**乘方**

    - tf.pow(x, a) /或者 x**a: 
$$y = x^a$$
    - 平方：tf.square(x)
    - 平方根：tf.sqrt(x)

In [45]:
x = tf.range(4)
tf.pow(x, 3)

<tf.Tensor: id=115, shape=(4,), dtype=int32, numpy=array([ 0,  1,  8, 27])>

In [46]:
x**3

<tf.Tensor: id=117, shape=(4,), dtype=int32, numpy=array([ 0,  1,  8, 27])>

In [48]:
x = tf.range(5)
x = tf.cast(x, dtype=tf.float32)
tf.square(x)

<tf.Tensor: id=129, shape=(5,), dtype=float32, numpy=array([ 0.,  1.,  4.,  9., 16.], dtype=float32)>

In [49]:
tf.sqrt(x)

<tf.Tensor: id=130, shape=(5,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       ],
      dtype=float32)>

**指数、对数**
    
    - tf.pow(a, x) 或者 ** 
$$x^a$$
    - tf.exp(x):
$$e^x$$
    - tf.math.log(x):
$$\log_ex$$
    - 如果希望计算其他底数的对数，可以利用换底公式：
$$\log_ax = \frac{\log_ex}{\log_ea}$$

### 5. 矩阵相乘

- 条件：a 的倒数第一个维度长度(列)和 b 的倒数第二个维度长度(行)必须相等。
- 比如 a shape:[4,3,28,32]可以与张量 b shape:[4,3,32,2]进行矩阵相乘
      - tf.matmul(a, b) 或者 @

In [50]:
a = tf.random.normal([4,3,23,32]) 
b = tf.random.normal([4,3,32,2]) 

In [51]:
a@b

<tf.Tensor: id=143, shape=(4, 3, 23, 2), dtype=float32, numpy=
array([[[[ -3.7281022 ,  -0.5481143 ],
         [ -2.5289836 ,  -7.7391057 ],
         [ -4.9118567 ,  -7.247255  ],
         [ -3.2518718 ,   3.28695   ],
         [ -4.4585943 ,  -7.1668806 ],
         [ -3.536016  ,  -4.7444386 ],
         [ -2.5934117 ,   2.9890685 ],
         [  0.28341842,  -3.4216423 ],
         [ -0.90658116,   2.5143228 ],
         [ -0.11950827,  -6.164032  ],
         [ -4.1975727 ,   2.690537  ],
         [  0.952472  ,  -1.670991  ],
         [ -3.5887825 ,  -2.4879065 ],
         [  5.7915316 ,   5.4631405 ],
         [  6.887642  ,  -2.5512424 ],
         [  2.070585  ,  -9.157738  ],
         [ -0.4712479 ,   9.485025  ],
         [  3.6912732 ,   2.3340733 ],
         [  9.4519    ,   7.40597   ],
         [ -0.7189307 ,  -9.064055  ],
         [ -1.2417998 ,   5.4572954 ],
         [ -0.6298633 ,   2.0502796 ],
         [ -4.1185055 ,  -6.5412703 ]],

        [[ -6.049983  ,  -0.06215966],

**注意：矩阵相乘函数支持自动 Broadcasting 机制：**

In [52]:
a = tf.random.normal([4,28,32]) 
b = tf.random.normal([32,16]) 
tf.matmul(a,b)

<tf.Tensor: id=156, shape=(4, 28, 16), dtype=float32, numpy=
array([[[  1.9768448 ,  -0.57617867,  -5.6353865 , ...,  -5.329978  ,
           0.06482008,  -4.104768  ],
        [  4.632547  ,   1.2486314 ,  -4.8302383 , ...,   2.8100548 ,
          -3.2217243 ,   2.0777693 ],
        [ 15.179934  ,   3.9330263 ,  -0.02730425, ...,   5.827208  ,
          -5.414667  ,  -2.1594887 ],
        ...,
        [ -2.1285815 ,  -1.1521646 ,  -4.5500255 , ...,  -0.1878823 ,
          -5.2772727 ,   6.992882  ],
        [  6.9222817 ,  -0.16247024,  -7.689714  , ...,  -6.1585565 ,
           6.1634617 ,   0.92403054],
        [ -2.5883725 ,  -8.376416  ,  -1.7047656 , ..., -11.042834  ,
           6.0730577 ,  -0.59936833]],

       [[  2.621737  ,  -2.9177177 ,   7.1339636 , ...,   7.4514093 ,
          -3.5549355 ,  -6.297744  ],
        [ -5.747243  ,  -5.4525905 ,   8.043662  , ...,   7.5935154 ,
          -0.5756688 ,  -1.7290642 ],
        [  0.15443516,   3.9258769 ,  -3.8513439 , ...,  -1.