# TensorFlow 基础（2）

### 1. 索引

In [1]:
import tensorflow as tf

In [2]:
x = tf.random.normal([4, 32, 32, 3])

In [9]:
# 取第一张图片第 2 行， 第 3 列，B 通道
x[0][1][2][1]

<tf.Tensor: id=85, shape=(), dtype=float32, numpy=-1.1656297>

In [10]:
# 也可以如下写法
x[0, 1, 2, 1]

<tf.Tensor: id=89, shape=(), dtype=float32, numpy=-1.1656297>

### 2. 切片

In [15]:
# 读取第 2，3 张图片的第 2 行第 3 列
x[1:3, 1, 2]

<tf.Tensor: id=105, shape=(2, 3), dtype=float32, numpy=
array([[ 1.2572367 , -2.7679925 , -0.34601206],
       [-0.2336391 , -1.2699697 , -1.6144751 ]], dtype=float32)>

In [18]:
# 读取第 1-2 张图片的 G/B 通道数据
# x[0:2,...,1:] 

### 3. 维度变换

**改变维度**
**reshape()**

In [20]:
x = tf.range(96)

In [21]:
x = tf.reshape(x, [2, 4, 4, 3])

**x.ndim 和 x.shape**

In [23]:
x.shape

TensorShape([2, 4, 4, 3])

In [24]:
x.ndim

4

**增加维度**

      - tf.expend_dims(x, axis)

In [41]:
x = tf.random.uniform([4, 4], maxval=10, dtype=tf.int32)
y = tf.random.uniform([4, 4], maxval=10, dtype=tf.int32)

In [42]:
x

<tf.Tensor: id=147, shape=(4, 4), dtype=int32, numpy=
array([[8, 8, 7, 5],
       [6, 2, 4, 4],
       [1, 0, 8, 7],
       [0, 4, 5, 8]])>

In [43]:
# 在最前面插入一个维度
x = tf.expand_dims(x, axis=0)

In [44]:
x.shape

TensorShape([1, 4, 4])

In [45]:
x

<tf.Tensor: id=153, shape=(1, 4, 4), dtype=int32, numpy=
array([[[8, 8, 7, 5],
        [6, 2, 4, 4],
        [1, 0, 8, 7],
        [0, 4, 5, 8]]])>

In [46]:
# 在 y 的最后面插入一个维度
y = tf.expand_dims(y, axis=2)

In [47]:
y.shape

TensorShape([4, 4, 1])

In [48]:
y

<tf.Tensor: id=155, shape=(4, 4, 1), dtype=int32, numpy=
array([[[4],
        [6],
        [6],
        [1]],

       [[8],
        [9],
        [6],
        [1]],

       [[7],
        [5],
        [2],
        [0]],

       [[9],
        [5],
        [0],
        [5]]])>

**删除维度**

- 每次只能删除一个维度
- 如果不指定维度参数 axis，即 tf.squeeze(x)，那么他会默认删除所有长度为 1 的维度
      - tf.squeeze(x, axis)

In [49]:
# 删除 x 第一个维度
x = tf.squeeze(x, axis=0)

In [50]:
x.shape

TensorShape([4, 4])

In [51]:
# 删除 y 的最后一个维度
y = tf.squeeze(y, axis=2)

In [52]:
y.shape

TensorShape([4, 4])

**交换维度**

- 注意：交换维度。改变了张量的**存储顺序**，同时也改变了张量的**视图**
      - tf.transpose(x, perm)

In [58]:
x = tf.random.normal([2, 32, 32, 3])

In [59]:
x.shape

TensorShape([2, 32, 32, 3])

In [60]:
y = tf.transpose(x, perm=[0, 3, 1, 2])

In [61]:
y.shape

TensorShape([2, 3, 32, 32])

**数据复制**

    - tf.tile(b, multiples)

In [67]:
b = tf.constant([1, 2, 3])

# 也可以使用 reshape 方法
# b = tf.reshape(b, [-1, 3])
b = tf.expand_dims(b, axis=0)

In [68]:
b

<tf.Tensor: id=184, shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]])>

In [70]:
b = tf.tile(b, multiples=[2, 1])

In [71]:
b

<tf.Tensor: id=186, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]])>

In [72]:
b.shape

TensorShape([2, 3])

In [74]:
# -------------------
x = tf.range(4)
x = tf.reshape(x, [2, 2])
x

<tf.Tensor: id=192, shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]])>

In [75]:
x = tf.tile(x, multiples=[1, 2])
x

<tf.Tensor: id=194, shape=(2, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3]])>

In [76]:
x = tf.tile(x, multiples=[2, 1])
x

<tf.Tensor: id=196, shape=(4, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]])>