# 多元线性回归-正规方程

[![LR9.png](https://i.postimg.cc/NMwQDTGT/LR9.png)](https://postimg.cc/LqNd6J16)

[![LR10.png](https://i.postimg.cc/jjfsyvTt/LR10.png)](https://postimg.cc/XZVSbfXz)

[![LR11.png](https://i.postimg.cc/sD0y8bD3/LR11.png)](https://postimg.cc/YhgJLnWP)

- **即是多元线性回归的正规方程解（Normal Equation）**
- 问题：时间复杂度高：O(n^3)
- 优点：不需要对数据做归一化处理

### 2. 动手实现

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
boston = datasets.load_boston()

X = boston.data
y = boston.target

X[1, :]

array([2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
       6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
       1.7800e+01, 3.9690e+02, 9.1400e+00])

In [3]:
X = X[y < 50.0]
y = y[y < 50.0]

In [4]:
X.shape

(490, 13)

In [5]:
from LR.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, seed=666)

In [7]:
from LR.LinearRegression import LinearRegression

In [8]:
reg = LinearRegression()

In [9]:
reg.fit_normal(X_train, y_train)

LinearRegression()

In [10]:
reg.coef_

array([-1.20354261e-01,  3.64423279e-02, -3.61493155e-02,  5.12978140e-02,
       -1.15775825e+01,  3.42740062e+00, -2.32311760e-02, -1.19487594e+00,
        2.60101728e-01, -1.40219119e-02, -8.35430488e-01,  7.80472852e-03,
       -3.80923751e-01])

In [12]:
reg.intercept_

34.11739972320428

In [13]:
reg.score(X_test, y_test)

0.8129794056212832

### 3. scikit-learn中的线性回归

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
lin_reg = LinearRegression()

In [16]:
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [17]:
lin_reg.coef_

array([-1.20354261e-01,  3.64423279e-02, -3.61493155e-02,  5.12978140e-02,
       -1.15775825e+01,  3.42740062e+00, -2.32311760e-02, -1.19487594e+00,
        2.60101728e-01, -1.40219119e-02, -8.35430488e-01,  7.80472852e-03,
       -3.80923751e-01])

In [18]:
lin_reg.intercept_

34.117399723229845

In [19]:
lin_reg.score(X_test, y_test)

0.8129794056212809

### 4. 使用scikit-learn中的kNN Regression 解决回归问题

In [20]:
from sklearn.neighbors import KNeighborsRegressor

In [21]:
knn_reg = KNeighborsRegressor()
knn_reg.fit(X_train, y_train)
knn_reg.score(X_test, y_test)

0.5865412198300899

- **显然，kNN预测分数低于线性回归模型的分数**
- 下面对 kNN 使用网格搜索找到最佳超参数

In [23]:
from sklearn.model_selection import GridSearchCV

param_grid = [
    {
        'weights': ['uniform'],
        'n_neighbors': [i for i in range(1, 11)]
    },
    {
        'weights': ['distance'],
        'n_neighbors': [i for i in range(1, 11)],
        'p': [i for i in range(1, 6)]
    }
]

In [24]:
knn_reg = KNeighborsRegressor()
grid_search = GridSearchCV(knn_reg, param_grid, n_jobs=-1, verbose=1)
grid_search.fit(X_train, y_train)

D:\appCommon\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.


Fitting 3 folds for each of 60 candidates, totalling 180 fits


[Parallel(n_jobs=-1)]: Done 180 out of 180 | elapsed:    3.4s finished
D:\appCommon\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform'),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid=[{'weights': ['uniform'], 'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}, {'weights': ['distance'], 'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'p': [1, 2, 3, 4, 5]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=1)

In [25]:
grid_search.best_params_

{'n_neighbors': 5, 'p': 1, 'weights': 'distance'}

In [26]:
grid_search.best_score_ # 此时是网格搜索自己的评估算法

0.6340477954176972

In [27]:
# 此时使用和线性回归相同的评估算法，可以看出，得分有很大的提高，但仍然不如线性回归模型
grid_search.best_estimator_.score(X_test, y_test)

0.7044357727037996