# 01. Numpy.array基础

- np.array()
- np.zeros(10, dtype=)
- np.zeros([3, 5], dtype=)
- np.zeros(shape=(3, 5), dtype=)
- np.ones()
- np.full(shape=, full_value=)
- np.arange()
- np.linspace()
- np.random.randint(low=, hight=, size=, dtype=)
- np.random.seed()
- np.random.random(size=)
- np.random.normal(, , , )

In [1]:
import numpy

In [2]:
numpy.__version__

'1.16.2'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.16.2'

### 1. Python List 的特点

In [5]:
L = [i for i in range(10)]

L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [7]:
L[5] = "Machine Learning"
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

**python 数组:** 只能存储同一类型元素

In [8]:
import array 

In [9]:
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[5]

5

In [11]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [12]:
arr[5] = "machine learning"

TypeError: an integer is required (got type str)

### 2. Numpy.array

**只能存储同一元素**

In [13]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [15]:
nparr[5] = "Machine Learning"

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [16]:
nparr.dtype

dtype('int32')

In [17]:
nparr[5] = 5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
nparr[3] = 3.14
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
nparr2 = np.array([1, 2, 3.0])
nparr2

array([1., 2., 3.])

In [20]:
nparr2.dtype

dtype('float64')

### 3. 其他创建numpy.array的方法

In [21]:
np.zeros(10)  # 生成全为零的数组

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10).dtype # 查看类型

dtype('float64')

In [23]:
np.zeros(10, dtype=int) # 指定类型

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.zeros([3, 5]) # 生成二维数组

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
np.ones([3, 5]) # 生成全为 1 的二维数组

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.full([3, 5], 6)
# np.full(shape=[3, 5], fill_value=6)
# np.full(fill_value=6, shape=[3, 5])

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

### arrage

In [31]:
# python 中的 range(起始点--包含， 终止点--不包含， 步长--只能为整数)
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [32]:
# numpy 中的 arange() 步长可以为浮点数，其余相同
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

### linspace

In [34]:
# 等差数列，前闭后闭，在0-20中分10段
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [35]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [36]:
# 生成一个从 0 到 10 之间（前闭后开）的随机整数
np.random.randint(0, 10)

4

In [37]:
# 生成 5 个 0 到 10 间（前闭后开）的随机数组成向量
np.random.randint(0, 10, 5)
# np.random.randint(0, 10, size = 5)

array([5, 2, 5, 6, 1])

In [39]:
np.random.randint(0, 10, size = (3, 5)) # 随机生成一个三行五列的数组，元素在 0 - 10 之间随机取值

array([[7, 6, 6, 4, 0],
       [4, 9, 4, 1, 7],
       [6, 2, 6, 2, 5]])

In [40]:
# 设置随机种子 
np.random.seed(111)
np.random.randint(0, 10, size = (3, 5))

array([[4, 4, 4, 6, 3],
       [9, 2, 6, 2, 8],
       [7, 9, 7, 1, 0]])

In [42]:
np.random.seed(111)
np.random.randint(0, 10, size = (3, 5))

array([[4, 4, 4, 6, 3],
       [9, 2, 6, 2, 8],
       [7, 9, 7, 1, 0]])

In [43]:
np.random.random()  # 生成随机浮点数， 0 - 1 之间

0.33765619188879237

In [44]:
np.random.random(10)  # 生成 10 个随机浮点数

array([0.99071246, 0.23772645, 0.08119266, 0.66960024, 0.62124292,
       0.27425353, 0.46622141, 0.11836775, 0.07395756, 0.90077418])

In [46]:
np.random.random((3, 5))

array([[0.79396256, 0.84056965, 0.81520746, 0.99095485, 0.57727383],
       [0.81376692, 0.42131788, 0.02744796, 0.45413664, 0.10532609],
       [0.81722006, 0.69772773, 0.5652854 , 0.2742273 , 0.99847374]])

In [47]:
np.random.normal()

0.31842788216526247

In [49]:
# 生成均值为 10， 方差为 100 的浮点数
np.random.normal(10, 100)

-243.67832910021

In [55]:
np.random.normal(0, 1, size=8)

array([-1.36123267, -1.32298164, -0.11531273, -0.88442736,  0.37722743,
        0.37430909,  0.80202648,  1.04621542])

In [56]:
np.random.normal?

In [57]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap