## Numpy.array 的基本操作

- x.ndim
- x.size
- x.shape
- x.reshape
- x[:2, :3]
- x[:2, ::2]
- x.copy()
- np.concatenate([], axis=)
- np.vstack([])
- np.hstack([])
- np.split(, , axis=)
- np.vsplit()
- np.hsplit()

In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### reshape

In [3]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [4]:
x.ndim

2

In [5]:
x.shape

(3, 5)

In [6]:
x.size

15

### numpy.array 数据访问

In [10]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
y[1]

1

In [12]:
y[-1]

9

In [13]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
x[(0, 0)]

0

In [15]:
x[2, 2]

12

In [17]:
y[0:5]
# y[:5]

array([0, 1, 2, 3, 4])

In [19]:
y[5:]

array([5, 6, 7, 8, 9])

In [20]:
# 第三个参数是步长
y[::2]

array([0, 2, 4, 6, 8])

In [22]:
y[::-2]

array([9, 7, 5, 3, 1])

In [23]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
# 取 x 的前两行前三列
x[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [25]:
x[:2][:3] # 取 x[:2]数组的前三个元素，但 x[:2]一共只有两个元素，故全取

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
x[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [28]:
x[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [29]:
# 二维数组取第一行
#x[0]
x[0, :]

array([0, 1, 2, 3, 4])

In [30]:
# 二维数组取第一列
x[:, 0]

array([ 0,  5, 10])

In [31]:
subx = x[:2, :3]
subx

array([[0, 1, 2],
       [5, 6, 7]])

In [32]:
# 在 python 中，修改子矩阵，父矩阵不改变
# 在 numpy 中，子矩阵是对父矩阵的引用，修改子矩阵后，父矩阵也会改变
subx[0, 0] = 100
subx

array([[100,   1,   2],
       [  5,   6,   7]])

In [33]:
x

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [34]:
x[0,0] = 0
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
subx

array([[0, 1, 2],
       [5, 6, 7]])

### copy()

In [36]:
# 如果不想让子矩阵和父矩阵有关联，使用 copy() 函数

In [37]:
subx2 = x[:2, :3].copy()
subx2

array([[0, 1, 2],
       [5, 6, 7]])

### Reshape 改变数组维度

In [38]:
y.shape

(10,)

In [41]:
y.ndim

1

In [39]:
x.shape

(3, 5)

In [40]:
y.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
y.ndim  # reshape 后，不改变 y自身

1

In [44]:
Y = y.reshape(2, 5)
Y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
Y.ndim

2

In [46]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
B = y.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [48]:
B.ndim

2

In [49]:
B.shape

(1, 10)

In [50]:
y.shape

(10,)

In [51]:
y.reshape(10, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [52]:
y.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 合并操作

In [53]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [54]:
np.concatenate([x, y])  # 合并操作 数组中可以有多个元素

array([1, 2, 3, 3, 2, 1])

In [55]:
# 二维数组合并

In [57]:
A = np.array([[1, 2, 3], [3, 2, 1]])

In [58]:
np.concatenate([A, A])  # 行拼接

array([[1, 2, 3],
       [3, 2, 1],
       [1, 2, 3],
       [3, 2, 1]])

In [59]:
np.concatenate([A, A], axis = 1)  # 列拼接

array([[1, 2, 3, 1, 2, 3],
       [3, 2, 1, 3, 2, 1]])

In [60]:
z = np.array([6, 6, 6])

In [63]:
# 方法1：可以把 z 转化为 二维矩阵，进行拼接
A2 = np.concatenate([A, z.reshape(1, -1)])
A2

array([[1, 2, 3],
       [3, 2, 1],
       [6, 6, 6]])

In [64]:
# 方法2：使用 vstack 方法

In [65]:
np.vstack([A, z])

array([[1, 2, 3],
       [3, 2, 1],
       [6, 6, 6]])

In [66]:
B = np.full((2, 3), 10)
B

array([[10, 10, 10],
       [10, 10, 10]])

In [67]:
np.hstack([A, B])

array([[ 1,  2,  3, 10, 10, 10],
       [ 3,  2,  1, 10, 10, 10]])

### 数据的分割

In [68]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
x1, x2, x3 = np.split(x, [3, 6])  # 以 3 和 6 为分割点，把数组分割为三段

In [70]:
x1

array([0, 1, 2])

In [71]:
x2

array([3, 4, 5])

In [72]:
x3

array([6, 7, 8, 9])

#### 二维分割

In [73]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
A1, A2 = np.split(A, [2])  # 默认水平分割

In [75]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [76]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [77]:
A1, A2 = np.split(A, [2], axis=1)

In [78]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [79]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

#### vsplit and hsplit

In [80]:
upper, lower = np.vsplit(A, [2])

In [81]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [82]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
left, right = np.hsplit(A, [2])

In [85]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [86]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])