## numpy.array 中矩阵的运算

- X / 2
- X // 2
- X ** 2
- X & 2 ???
- np.abs(x)
- np.sin(x)
- np.exp(x)
- np.power(3, x) # 求 3 的 x 次方 == (3 ** x)
- np.log(x)
- np.log2(x)
- X.dot()
- X.T
- np.linalg.inv(X) # 求逆运算
- np.linalg.pinv(X) # 求伪逆运算

L = [1, 3, 2]

2 * L = ?

In [1]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
A = []
for i in L:
    A.append(2 * i)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [4]:
n = 100000
L = [i for i in range(n)]

In [8]:
%%time
A = []
for i in L:
    A.append(2 * i)


Wall time: 23 ms


In [9]:
%%time
A = [2*i for i in L]

Wall time: 7.01 ms


In [10]:
# 使用 numpy 
import numpy as np
L = np.arange(n)

In [12]:
%%time
A = np.array(2*i for i in L)

Wall time: 0 ns


In [15]:
n = 10
L = np.arange(n)
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Functions

In [18]:
X = np.arange(16).reshape(4, 4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
X / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5],
       [6. , 6.5, 7. , 7.5]])

In [20]:
X // 2  # 整数除法

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5],
       [6, 6, 7, 7]], dtype=int32)

In [21]:
X ** 2 # 平方

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]], dtype=int32)

In [22]:
X & 2  # 取余

array([[0, 0, 2, 2],
       [0, 0, 2, 2],
       [0, 0, 2, 2],
       [0, 0, 2, 2]], dtype=int32)

In [23]:
np.abs(X)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
np.sin(X)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [25]:
np.exp(X)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])

In [26]:
np.power(3, X)  # 求 3 的 X 次方

array([[       1,        3,        9,       27],
       [      81,      243,      729,     2187],
       [    6561,    19683,    59049,   177147],
       [  531441,  1594323,  4782969, 14348907]], dtype=int32)

In [27]:
3 ** X

array([[       1,        3,        9,       27],
       [      81,      243,      729,     2187],
       [    6561,    19683,    59049,   177147],
       [  531441,  1594323,  4782969, 14348907]], dtype=int32)

In [28]:
np.log(X)

D:\appCommon\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [30]:
np.log2(X)

D:\appCommon\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 , 2.80735492],
       [3.        , 3.169925  , 3.32192809, 3.45943162],
       [3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [31]:
np.log10(X)

D:\appCommon\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125, 0.84509804],
       [0.90308999, 0.95424251, 1.        , 1.04139269],
       [1.07918125, 1.11394335, 1.14612804, 1.17609126]])

### 矩阵运算

In [33]:
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [34]:
B = np.full((2, 2), 10)
B

array([[10, 10],
       [10, 10]])

In [35]:
A.dot(B) # 矩阵相乘

array([[10, 10],
       [50, 50]])

In [36]:
A.T  # 矩阵转置

array([[0, 2],
       [1, 3]])

### 向量和矩阵的运算

In [37]:
v = np.array([1, 2])
v

array([1, 2])

In [38]:
A

array([[0, 1],
       [2, 3]])

#### 加法

In [39]:
# 向量和矩阵相加：向量和矩阵中的每一行做加法
A + v

array([[1, 3],
       [3, 5]])

In [45]:
# 也可以先把向量转化为矩阵，然后做加法
# A.shape // (2, 2)
# A.shape[0]  // 2
# A.sjape[1]  // 2
np.vstack([v] * A.shape[0])

# 使用 tile 方法
# np.tile(v, [2, 1])  
# 表示向量 v 在行向量上堆叠 2 次， 在列向量上堆叠 1 次

array([[1, 2],
       [1, 2]])

In [46]:
np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [47]:
np.tile(v, [2, 1]) + A

array([[1, 3],
       [3, 5]])

#### 乘法

In [48]:
v * A

array([[0, 2],
       [2, 6]])

In [49]:
v.dot(A)

array([4, 7])

In [50]:
A.dot(v)  # 自动把 v 转化为列向量

array([2, 8])

### 矩阵的逆

In [51]:
A

array([[0, 1],
       [2, 3]])

In [53]:
invA = np.linalg.inv(A)
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [54]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [55]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [56]:
B = np.arange(16).reshape(2, 8)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [57]:
np.linalg.inv(B)

LinAlgError: Last 2 dimensions of the array must be square

In [59]:
# 对于没有逆矩阵的矩阵，我们可以求其伪逆矩阵
invB = np.linalg.pinv(B)
invB

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [60]:
invB.shape

(8, 2)

In [61]:
B.dot(invB)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])